### ISSUE TITLE
Non-UTC timezone in WasteContainer examples

### ISSUE THREAD

**Issue by fbattello** [smart-data-models/dataModel.WasteManagement#11]
Hi,

`WasteContainer` examples have 2 temporal properties `binClearedTime` and `binLoggedTime` with a non-UTC datetime value.
Should `2021-03-11T15:51:02+05:30` be replaced by its equivalent in UTC `2021-03-11T10:21:02Z` ?

**Comment by albertoabellagarcia** [comment]
Checking....

**Comment by albertoabellagarcia** [comment]
You can ingest the data in a non-UTC but the broker would convert it to UTC.
