### ISSUE TITLE
WasteContainer (storedWasteKind) enum, other values?

### ISSUE THREAD

**Issue by modularTaco** [smart-data-models/dataModel.WasteManagement#8]
Hey,

in the [WasteContainer schema](https://github.com/smart-data-models/dataModel.WasteManagement/blob/master/WasteContainer/schema.json]) `storedWasteKind` is defined as enum.  
But the description says:

> [...] Or any other value which does not fit within the former. 

Which sounds to me like a WasteContainer entity with `{ "storedWasteKind": "clothes" }` should be valid.  
But after validating the jsonschema it turns out, it's not.  
Obviously only the values listed in the enum can be used.

Am I misinterpreting the description, or is this a bug?

As I need `clothes` as waste kind and want to use this schema, I have the following options:
1. Fork the schema, add `clothes` to the `storedWasteKind` enum and use my fork (and/or open a PR)
2. Fork the schema, remove the enum from  `storedWasteKind` so the schema matches the description and use my fork (and/or open a PR)
3. Use `other` as `storedWasteKind` and specify `clothes` in another attribute (not ideal)
4. do not validate json objects against this schema (not ideal)

Am i missing something? If not, what would you prefer, option 1 or 2?

**Comment by albertoabellagarcia** [comment]
Simpler solution 1. Make a PR with clothes added to the enum.
Thanks

**Comment by modularTaco** [comment]
> Simpler solution 1. Make a PR with clothes added to the enum.
> Thanks

Okay, i've created a PR.

But what about the description:

> [...] Or any other value which does not fit within the former.

This sounds like i could use any value, not only the ones listed in the enum. Should we change this description or doesn't this look as confusing to you as it does to me?

**Comment by albertoabellagarcia** [comment]
context broker does not stop you to use any other value, and if you need that other value should be standardized. We'll be open to review it, like clothes.
